services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  kanwoo-frontend:
    image: nextjs-standalone-image
    container_name: "cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:kanwoo-backend-$IMAGE_TAG"
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped