on:
    workflow_call:
        inputs:
            image-tag:
                required: true
                type: string
                description: Tag for docker image

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - name: Login to yandex cloud registry
              uses: yc-actions/yc-cr-login@v3
              with:
                yc-sa-id: ${{ secrets.YC_SA_ID}}
                
            - name: Build, tag, and push image to Yandex Cloud Container Registry
              env:
                CR_REGISTRY: ${{ vars.CR_REGISTRY }}
                CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
                IMAGE_TAG: ${{ inputs.image-tag }}
                NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
              run: |
                docker build \
                    --build-arg NEXT_PUBLIC_SITE_URL="https://staging.kanwoo.ru" \
                    -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
                    
                docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG 
