on:
    workflow_call:
        inputs:
            image-tag:
                required: true
                type: string
                description: Tag for docker image
            environment:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - name: Login to yandex cloud registry
              uses: yc-actions/yc-cr-login@v3
              with:
                yc-sa-id: ${{ secrets.YC_SA_ID}}
                
            - name: Build, tag, and push image to Yandex Cloud Container Registry
              env:
                IMAGE_TAG: ${{ inputs.image-tag }}
                CR_REGISTRY: ${{ vars.CR_REGISTRY }}
                CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
                NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
                NEXT_PUBLIC_CSRF_ACCESS_COOKIE_NAME: ${{ vars.NEXT_PUBLIC_CSRF_ACCESS_COOKIE_NAME }}
                NEXT_PUBLIC_CSRF_REFRESH_COOKIE_NAME: ${{ vars.NEXT_PUBLIC_CSRF_REFRESH_COOKIE_NAME }}
                NEXT_PUBLIC_YANDEX_OAUTH_CLIENT_ID: ${{vars.NEXT_PUBLIC_YANDEX_OAUTH_CLIENT_ID}}
                NEXT_PUBLIC_YANDEX_OAUTH_REDIRECT_URL: ${{vars.NEXT_PUBLIC_YANDEX_OAUTH_REDIRECT_URL}}
                NEXT_PUBLIC_YANDEX_OAUTH_ORIGIN: ${{vars.NEXT_PUBLIC_YANDEX_OAUTH_ORIGIN}}

              run: |
                echo $NEXT_PUBLIC_SITE_URL
                docker build \
                    --build-arg NEXT_PUBLIC_SITE_URL="$NEXT_PUBLIC_SITE_URL" \
                    --build-arg NEXT_PUBLIC_CSRF_ACCESS_COOKIE_NAME="$NEXT_PUBLIC_CSRF_ACCESS_COOKIE_NAME" \
                    --build-arg NEXT_PUBLIC_CSRF_REFRESH_COOKIE_NAME="$NEXT_PUBLIC_CSRF_REFRESH_COOKIE_NAME" \
                    -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .

                docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG 
