on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
                description: What environment use to deploy
            image-tag:
                required: true
                type: string


jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
        - name: Clone repo
          uses: actions/checkout@v3

        - name: Get Yandex Cloud IAM token
          id: get-iam-token
          uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
          with:
            yc-sa-id: ${{ secrets.YC_SA_ID}}

        - name: Copy docker compose file into host
          uses: appleboy/scp-action@v1
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            source: ${{ vars.COMPOSE_FILENAME }}
            target: ${{ vars.COMPOSE_DESTINATION_PATH }}
            debug: true


        - name: Start project
          uses: appleboy/ssh-action@v1
          env:
            YC_IAM_TOKEN: ${{ steps.get-iam-token.outputs.token }}
            CR_REGISTRY: ${{ vars.CR_REGISTRY }} 
            CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
            IMAGE_TAG: ${{ inputs.image-tag }}
            DOCKER_COMPOSE_PATH: ${{ vars.COMPOSE_DESTINATION_PATH }}
            DOCKER_COMPOSE_FILENAME: ${{ vars.COMPOSE_FILENAME }}
            API_URL: ${{vars.API_URL}}
            PORT: ${{vars.PORT}}
            PROJECT_NAME: ${{vars.PROJECT_NAME}}
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            envs: 
                YC_IAM_TOKEN, 
                CR_REGISTRY, 
                CR_REPOSITORY,
                DOCKER_COMPOSE_PATH,
                DOCKER_COMPOSE_FILENAME, 
                IMAGE_TAG,   
                API_URL,
                PROJECT_NAME,
                PORT
            script: |
                echo $YC_IAM_TOKEN|docker login \
                --username iam \
                --password-stdin \
                cr.yandex

                docker pull cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

                cd $DOCKER_COMPOSE_PATH

                docker compose -f $DOCKER_COMPOSE_FILENAME -p $PROJECT_NAME down

                docker compose -f $DOCKER_COMPOSE_FILENAME -p $PROJECT_NAME up -d

                docker image prune -a -f